### PR TITLE
Rough go at the dropdown buttons

### PR DESCRIPTION
**Pull request by AlexMLindemann**
Missing menu data values. Needs a lot of work. Do not merge!

### CODE REVIEW

**Comment by maxwell-jordan** [comment]
Good start at drop downs; clearly not ready to merge with main

**Comment by spencerjkim1** [comment]
I see the work you've done for the drop downs, if we can finish this up we can start working on implementing this for all the forms with the given responses we get from Garry.

**Review by spencerjkim1 — COMMENTED** [review]
Looking good so far need to fully implement

**Comment by Jacob-M-Smith** [comment]
Good work on the dropdowns, currently implemented functionality works well when loaded onto a device

**Comment by Jacob-M-Smith** [comment]
gonna close this since its not ready to merge

**Pull request closed without merging**
