### PR TITLE
added a list of keywords to associate with dropdown buttons for the hazard page

### PR DESCRIPTION
**Pull request by Jacob-M-Smith**
We will probably need multiple lists for each form, depending on which keywords are applicable to each entry box.

### CODE REVIEW

**Comment by maxwell-jordan** [comment]
good start at implementing drop downs

**Comment by spencerjkim1** [comment]
It's good that we have multiple people working on this issue as we need to implement the dropdowns instead of the fill-in boxes.

**Review by spencerjkim1 — COMMENTED** [review]
we need to implement the dropdowns instead of the fill-in boxes.

**Comment by amccrary6** [comment]
Great start. This could also serve as a good base for the other forms, since we need to implement dropdowns for each form

**Pull request merged**
